version: "3"
services:
  postgresql:
    image: postgres:13.4
    command: ["postgres", "-c", "log_statement=all"]
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "book-shelf"
      POSTGRES_PASSWORD: "book-shelf"
      POSTGRES_DB: "book-shelf"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      COMPOSE_PROJECT_NAME: "book-shelf"
